---
title: "02d_subsetforprojects.Rmd"
author: "Rayna M Harris"
date: "March 6, 2017"
output: md_document
---

Not all of my samples need to be processed together. This script will make the appropriate subset files. First, read in the new data

```{r install packages load data, warning=FALSE, message=FALSE}
library("dplyr") ## for filtering and selecting rows
library("plyr") ## for renaming factors
```


```{r dissociation}
DissociationCountData <- read.csv("../data/rnaseq/countbygene.csv", header=T, check.names = F, row.names = 1)
DissociationColData <- read.csv("../data/rnaseq/kallistosamples.csv", header=T)

DissociationColData <- DissociationColData %>%
  filter(Group %in% c("homecage", "control")) %>%
  filter(Genotype != "FMR1") %>%
  filter(!grepl("C|D|16-", Mouse))
savecols <- as.character(DissociationColData$RNAseqID) #selects all good samples
savecols <- as.vector(savecols) # make it a vector
DissociationCountData <- DissociationCountData %>% select(one_of(savecols)) # keep good samples

# save files to dissociation project directory
#write.csv(DissociationColData, "~/Github/DissociationTest/data/DissociationColData.csv", row.names=F)
#write.csv(DissociationCountData, "~/Github/DissociationTest/data/DissociationCountData.csv", row.names=T)
```


```{r fmr1}
fmr1CountData <- read.csv("../data/rnaseq/countbygene.csv", header=T, check.names = F, row.names = 1)
fmr1ColData <- read.csv("../data/rnaseq/kallistosamples.csv", header=T)

fmr1ColData <- fmr1ColData %>%
  filter(jobnumber == "JA17009")
savecols <- as.character(fmr1ColData$RNAseqID) #selects all good samples
savecols <- as.vector(savecols) # make it a vector
fmr1CountData <- fmr1CountData %>% select(one_of(savecols)) # keep good samples

# save files to dissociation project directory
#write.csv(fmr1ColData, "../data/rnaseq/fmr1ColData.csv", row.names=F)
#write.csv(fmr1CountData, "../data/rnaseq/fmr1CountData.csv", row.names=T)
```


```{r dissociation}
BehaviorSlimCountData <- read.csv("../data/rnaseq/countbygene.csv", header=T, check.names = F, row.names = 1)
BehaviorSlimColData <- read.csv("../data/rnaseq/kallistosamples.csv", header=T)

BehaviorSlimColData <- BehaviorSlimColData %>%
  filter(Group %in% c("consistent", "control")) %>%
  filter(Genotype != "FMR1") %>%
  filter(!grepl("16-", Mouse)) %>%
  filter(Conflict != "Conflict")
savecols <- as.character(BehaviorSlimColData$RNAseqID) #selects all good samples
savecols <- as.vector(savecols) # make it a vector
BehaviorSlimCountData <- BehaviorSlimCountData %>% select(one_of(savecols)) # keep good samples

# save files to dissociation project directory
write.csv(BehaviorSlimColData, "~/Github/DissociationTest/data/BehaviorSlimColData.csv", row.names=F)
write.csv(BehaviorSlimCountData, "~/Github/DissociationTest/data/BehaviorSlimCountData.csv", row.names=T)
```

## Session Info
```{r SessionInfo}
sessionInfo()
```